# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensorA = torch.randn(7, 7)
tensorA, tensorA.shape

(tensor([[ 0.3645, -1.0577,  0.6551, -0.3634,  0.3944,  0.7552, -1.0411],
         [ 0.4111, -0.1565, -0.6202,  0.1441, -0.8584,  0.8997,  0.3081],
         [ 0.6186, -0.6242,  2.8101,  1.3002,  0.4588,  0.8301, -1.6198],
         [ 1.1083, -0.2889, -1.1439, -0.5319, -0.7232,  1.2792,  0.8470],
         [ 0.8594,  0.0661,  1.2016, -1.2470, -0.6489, -1.1776, -0.7159],
         [-1.6890,  0.5348, -0.1385, -0.9677, -1.6586, -1.1589,  0.6552],
         [-0.7036, -0.2632,  0.0707,  0.7554,  1.0935, -0.5718, -0.0387]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
tensorB = torch.randn(1, 7)
# Perform matrix multiplication 
tensorA @ tensorB.T

tensor([[-2.1101],
        [ 2.4709],
        [-1.7685],
        [ 3.5836],
        [ 0.6642],
        [ 0.0749],
        [-4.0024]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [14]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensorA = torch.randn(7, 7)
tensorB = torch.randn(1, 7)

# Matrix multiply tensors
tensorA @ tensorB.T


tensor([[ 3.5168],
        [ 2.1984],
        [-1.7815],
        [ 3.8600],
        [-1.5010],
        [-1.6916],
        [-2.9352]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
# Set random seed on the GPU (MPS for Apple Silicon)
torch.mps.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [17]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.randn(2, 3, device=device)
tensor_B = torch.randn(2, 3, device=device)
tensor_A, tensor_B


Device: mps


(tensor([[-0.0516,  0.7090,  0.9474],
         [ 0.8520,  0.3647, -1.5575]], device='mps:0'),
 tensor([[-2.0092,  2.2507, -0.6096],
         [ 1.3548,  0.7295,  1.2154]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [19]:
# Perform matmul on tensor_A and tensor_B
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 1.1220,  1.5989],
        [ 0.0583, -0.4727]], device='mps:0')

### 8. Find the maximum and minimum values of the output of 7.

In [20]:
# Find max
output = torch.matmul(tensor_A, tensor_B.T)
max_value = output.max()
print(f"Max value: {max_value}")

# Find min
min_value = output.min()
print(f"Min value: {min_value}")


Max value: 1.5988517999649048
Min value: -0.4726644456386566


### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max
argmax_value = output.argmax()
print(f"Arg max: {argmax_value}")

# Find arg min
argmin_value = output.argmin()
print(f"Arg min: {argmin_value}")


Arg max: 1
Arg min: 3



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [22]:
# Set seed
torch.manual_seed(1234)

# Create random tensor
tensor_a = torch.randn(1, 1, 1, 10)

# Remove single dimensions
tensor_a.squeeze()

# Print out tensors and their shapes
tensor_a, tensor_a.shape, tensor_a.squeeze(), tensor_a.squeeze().shape


(tensor([[[[ 0.0461,  0.4024, -1.0115,  0.2167, -0.6123,  0.5036,  0.2310,
             0.6931, -0.2669,  2.1785]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([ 0.0461,  0.4024, -1.0115,  0.2167, -0.6123,  0.5036,  0.2310,  0.6931,
         -0.2669,  2.1785]),
 torch.Size([10]))